CREATE TABLE Reader (
    UserId INTEGER PRIMARY KEY AUTOINCREMENT,
    Username NVARCHAR(24) NOT NULL,
    Password NVARCHAR(24) NOT NULL
);

CREATE TABLE Book (
    ISBN NVARCHAR(17) PRIMARY KEY NOT NULL,
    Title NVARCHAR(255) NOT NULL,
    YearPublished INTEGER NOT NULL
);

CREATE TABLE Author (
    AuthorId INTEGER PRIMARY KEY AUTOINCREMENT,
    Country NVARCHAR(56) NOT NULL,
    FirstName NVARCHAR(24) NOT NULL,
    LastName NVARCHAR(24) NOT NULL
);

CREATE TABLE Reads (
    Rating NUMERIC(3,2) NOT NULL,
    ISBN NVARCHAR(17) NOT NULL,
    UserId INTEGER NOT NULL,
    CONSTRAINT fk_Reads_Book FOREIGN KEY (ISBN) REFERENCES Book(ISBN),
    CONSTRAINT fk_Reads_Reader FOREIGN KEY (UserId) REFERENCES Reader(UserId)
);

CREATE TABLE Writes (
    ISBN NVARCHAR(17) NOT NULL,
    AuthorId INTEGER NOT NULL,
    CONSTRAINT fk_Writes_Book FOREIGN KEY (ISBN) REFERENCES Book(ISBN),
    CONSTRAINT fk_Writes_Author FOREIGN KEY (AuthorId) REFERENCES Author(AuthorId)
);
    